# Site settings
title: OOOC De Zandberg
email: info@zandberg.be
description: >-
  Gemaakt door Tom Kerkhove.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
theme: minima # Using the minima theme which is Jekyll's default
plugins:
  - jekyll-feed
  - jekyll-seo-tag

facebook_username: ooocdezandberg

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git
  - .github

# Collections
# collections:
#   staff:
#     output: true

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

header_pages:
  - missie.md
  - leefgroepwerking.md
  - context.md
  - professionelen.md
  - werk-bij-ons.md
  - partners.md
  - steun-ons.md
  - contact.md
